USE [YSB]

CREATE TABLE Animals
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE AttackMethods
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE AttackMethodCategories
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE TurningMethods
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE StandingMethods
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE AttackMethodForms
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE Strategies
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE Curriculums
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	AnimalID INT NOT NULL,
	StartDate DATETIME,
	EndDate DATETIME,
	TotalDays INT NOT NULL,
	DoneDays INT NOT NULL,
	RemainingDays INT NOT NULL,
	TotalWeeks DECIMAL(2,2) NOT NULL,
	DoneWeeks DECIMAL(2,2) NOT NULL,
	RemainingWeeks DECIMAL(2,2) NOT NULL,
	PercentageDone VARCHAR(255) NOT NULL
);

CREATE TABLE CurriculumItems
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	ParentCurriculumID INT NOT NULL,
	AttackMethodFormID INT NOT NULL,
	AttackMethodsID INT NOT NULL,
	StandingMethodsID INT NOT NULL,
	StrategiesID INT NOT NULL,
	TurningMethodsID INT NOT NULL
)